-- 006_contratos.sql
-- Tablas de contrato (coescritas) — ADR 0004. OutboxEvent, OutboxEventIntegracion, CommandQueue,
-- InboxEvent.

-- design.md item 10: monotonic per-aggregate sequence, fed into OutboxEvent.Secuencia. A SEQUENCE
-- is fine here (unlike CorrelativoAsiento) because a burned outbox sequence value is harmless —
-- the ADR 0006 objection to SEQUENCE/IDENTITY does not transfer.
CREATE SEQUENCE fact.SeqOutbox AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE fact.OutboxEvent
(
    OutboxEventId BIGINT IDENTITY(1,1) NOT NULL,
    Tipo           VARCHAR(30)         NOT NULL,
    FacturaId       BIGINT             NOT NULL,
    -- design.md item 9: NVARCHAR(MAX) — not VARBINARY (unreadable), not the json type (version not
    -- assumed). NVARCHAR because payloads carry accented names/glosas.
    Payload          NVARCHAR(MAX)     NOT NULL,
    -- design.md item 10: BIGINT, fed from fact.SeqOutbox.
    Secuencia         BIGINT           NOT NULL,
    Estado             VARCHAR(20)     NOT NULL CONSTRAINT DF_OutboxEvent_Estado DEFAULT ('PENDIENTE'),
    CreadoEn            DATETIME2(3)   NOT NULL CONSTRAINT DF_OutboxEvent_CreadoEn DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT PK_OutboxEvent PRIMARY KEY (OutboxEventId),
    CONSTRAINT FK_OutboxEvent_Factura FOREIGN KEY (FacturaId) REFERENCES fact.Factura (FacturaId),
    CONSTRAINT CK_OutboxEvent_Tipo CHECK (Tipo IN (
        'FACTURA_VALIDADA', 'FACTURA_CORREGIDA', 'ASIENTO_CORREGIDO', 'ASIENTO_ANULADO',
        'DOCUMENTACION_ACTUALIZADA'
    )),
    CONSTRAINT CK_OutboxEvent_Estado CHECK (Estado IN ('PENDIENTE', 'COMPLETADO'))
);

-- "Estado independiente por integración" (ADR 0004) — design.md's child-table decision.
CREATE TABLE fact.OutboxEventIntegracion
(
    OutboxEventId    BIGINT       NOT NULL,
    Integracion       VARCHAR(20) NOT NULL,
    Estado             VARCHAR(20) NOT NULL CONSTRAINT DF_OutboxEventIntegracion_Estado DEFAULT ('PENDIENTE'),
    -- design.md item 20: SMALLINT.
    Intentos            SMALLINT   NOT NULL CONSTRAINT DF_OutboxEventIntegracion_Intentos DEFAULT (0),
    ProximoIntentoEn     DATETIME2(3) NULL,
    -- design.md item 25.
    UltimoError            NVARCHAR(2000) NULL,
    ActualizadoEn           DATETIME2(3)  NULL,
    CONSTRAINT PK_OutboxEventIntegracion PRIMARY KEY (OutboxEventId, Integracion),
    CONSTRAINT FK_OutboxEventIntegracion_OutboxEvent
        FOREIGN KEY (OutboxEventId) REFERENCES fact.OutboxEvent (OutboxEventId),
    CONSTRAINT CK_OutboxEventIntegracion_Integracion
        CHECK (Integracion IN ('DRIVE', 'SHEETS', 'TELEGRAM', 'CORREO')),
    CONSTRAINT CK_OutboxEventIntegracion_Estado
        CHECK (Estado IN ('PENDIENTE', 'COMPLETADO', 'OBSOLETO', 'ERROR'))
);

CREATE TABLE fact.CommandQueue
(
    CommandQueueId BIGINT IDENTITY(1,1) NOT NULL,
    Tipo            VARCHAR(30)         NOT NULL,
    -- Generic reference; the referenced entity varies by Tipo (Procesamiento or DocumentoRecibido),
    -- so it stays unconstrained rather than forcing a wrong FK target.
    Referencia       BIGINT             NULL,
    Payload           NVARCHAR(MAX)     NOT NULL,
    Estado             VARCHAR(20)      NOT NULL CONSTRAINT DF_CommandQueue_Estado DEFAULT ('PENDIENTE'),
    -- design.md item 20: SMALLINT.
    Intentos            SMALLINT        NOT NULL CONSTRAINT DF_CommandQueue_Intentos DEFAULT (0),
    ProximoIntentoEn      DATETIME2(3)  NULL,
    -- design.md item 21: UNIQUEIDENTIFIER, generated by the API before the request touches the
    -- database, travels into logs across both runtimes.
    CorrelationId          UNIQUEIDENTIFIER NOT NULL,
    CreadoEn                DATETIME2(3)  NOT NULL CONSTRAINT DF_CommandQueue_CreadoEn DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT PK_CommandQueue PRIMARY KEY (CommandQueueId),
    CONSTRAINT CK_CommandQueue_Tipo
        CHECK (Tipo IN ('REPROCESAR_DOCUMENTO', 'SINCRONIZAR_GMAIL', 'SINCRONIZAR_SBS')),
    CONSTRAINT CK_CommandQueue_Estado CHECK (Estado IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'ERROR'))
);

CREATE TABLE fact.InboxEvent
(
    InboxEventId  BIGINT IDENTITY(1,1) NOT NULL,
    Tipo           VARCHAR(30)         NOT NULL,
    ProcesamientoId BIGINT             NOT NULL,
    Payload          NVARCHAR(MAX)     NOT NULL,
    EstadoConsumo     VARCHAR(20)      NOT NULL CONSTRAINT DF_InboxEvent_EstadoConsumo DEFAULT ('PENDIENTE'),
    ConsumidoEn        DATETIME2(3)    NULL,
    FacturaId           BIGINT         NULL,
    MotivoDescarte        NVARCHAR(300) NULL,
    CreadoEn               DATETIME2(3) NOT NULL CONSTRAINT DF_InboxEvent_CreadoEn DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT PK_InboxEvent PRIMARY KEY (InboxEventId),
    CONSTRAINT FK_InboxEvent_Procesamiento
        FOREIGN KEY (ProcesamientoId) REFERENCES fact.Procesamiento (ProcesamientoId),
    CONSTRAINT FK_InboxEvent_Factura FOREIGN KEY (FacturaId) REFERENCES fact.Factura (FacturaId),
    CONSTRAINT CK_InboxEvent_Tipo CHECK (Tipo IN ('PROCESAMIENTO_FINALIZADO')),
    CONSTRAINT CK_InboxEvent_EstadoConsumo CHECK (EstadoConsumo IN ('PENDIENTE', 'PROMOVIDO', 'DESCARTADO'))
);
